# Generated by Django 2.2.28 on 2024-11-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='character',
            name='team',
        ),
        migrations.RemoveField(
            model_name='character',
            name='type',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='photo',
        ),
        migrations.AddField(
            model_name='character',
            name='trajet',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='vol',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
