# Generated by Django 2.2.28 on 2024-11-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_auto_20241112_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='trajet',
            new_name='ligne',
        ),
        migrations.RemoveField(
            model_name='character',
            name='vol',
        ),
        migrations.AddField(
            model_name='character',
            name='compagnie',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
