# Generated by Django 2.2.28 on 2024-11-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_auto_20241112_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='photo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
