# Generated by Django 2.2.28 on 2024-11-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_character_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='logo_compagnie',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
