# Generated by Django 2.2.28 on 2024-11-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_character_logo_compagnie'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='failure',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='proba_failure',
            field=models.IntegerField(null=True),
        ),
    ]
