# Generated by Django 2.2.28 on 2024-11-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0006_auto_20241115_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='end_time_countdown',
            field=models.DateTimeField(null=True),
        ),
    ]
