# Generated by Django 2.2.28 on 2024-11-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0008_character_crashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='logo_compagnie',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
